#!/bin/sh

apt-get update
apt-get install -y --no-install-recommends \
	linux-headers-amd64 \
	flashcache-dkms \
	flashcache-utils \
	libpython2.7 \
	collectd \
	collectd-utils

flashcache_destroy /dev/sda || true
flashcache_create -p back cachedev1 /dev/sda /dev/sdb
flashcache_destroy /dev/sdc || true
flashcache_create -p back cachedev2 /dev/sdc /dev/sdd
cp /vagrant/vagrant/collectd.conf /etc/collectd/
service collectd restart
